# Generated by Django 4.2 on 2025-09-29 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cats", "0002_cat"),
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mission",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="target",
            options={"ordering": ["title"]},
        ),
        migrations.RemoveField(
            model_name="mission",
            name="status",
        ),
        migrations.AddField(
            model_name="mission",
            name="is_completed",
            field=models.BooleanField(
                default=False, help_text="The completion status of the mission."
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="cat",
            field=models.ForeignKey(
                blank=True,
                help_text="The cat assigned to this mission. Can be null.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="missions",
                to="cats.cat",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time when the mission was created.",
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="country",
            field=models.CharField(
                help_text="The country where the target is located.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="is_completed",
            field=models.BooleanField(
                default=False, help_text="The completion status of the target."
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="mission",
            field=models.ForeignKey(
                help_text="The mission this target is associated with.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targets",
                to="missions.mission",
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes or observations about the target.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="title",
            field=models.CharField(
                help_text="The title or name of the target.", max_length=200
            ),
        ),
    ]
