# Generated by Django 4.2 on 2025-09-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the spy cat.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        help_text="The number of years the cat has been a spy."
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        help_text="The breed of the spy cat.", max_length=100
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The salary of the spy cat.",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Spy Cat",
                "verbose_name_plural": "Spy Cats",
                "ordering": ["-years_of_experience", "name"],
            },
        ),
    ]
