# Generated by Django 4.2 on 2025-09-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cats", "0002_cat"),
        ("missions", "0002_alter_mission_options_alter_target_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cats",
        ),
    ]
